# Generated by Django 5.1.2 on 2024-11-19 11:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)])),
                ('problem_description', models.TextField(blank=True, null=True, verbose_name='Describe your problem')),
                ('sensation_spinning_objects', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Sensation of spinning objects')),
                ('staggering_to_one_side', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Staggering to one side')),
                ('dizziness_without_spinning', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Dizziness without spinning objects')),
                ('sinking_sensation', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Sinking sensation')),
                ('episodic_sensations', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Sensations occur in episodes')),
                ('dizziness_between_episodes', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Dizziness between episodes')),
                ('hearing_changes_during_attacks', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Hearing changes during attacks')),
                ('tinnitus_during_attacks', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Tinnitus during attacks')),
                ('tension_in_ears', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Tension in ears during attacks')),
                ('dizziness_while_standing_quickly', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Dizziness when standing quickly')),
                ('dizziness_during_position_changes', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Dizziness during position changes')),
                ('nausea_during_attacks', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Nausea during attacks')),
                ('headache_during_attacks', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Headache during attacks')),
                ('sensitivity_to_light_noise', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Sensitivity to light and noise during attacks')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
        ),
    ]
