# Generated by Django 5.1.2 on 2024-11-04 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='+359883427273', max_length=13, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
