# Generated by Django 5.1.2 on 2024-12-01 17:41

import django.core.validators
import otonevrolog_main.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clinicsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13), otonevrolog_main.accounts.validators.validate_phone_number]),
        ),
    ]
