# Generated by Django 5.1.2 on 2024-12-08 15:47

import django.core.validators
import otonevrolog_main.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsurvey',
            name='email',
            field=models.CharField(max_length=50, validators=[otonevrolog_main.accounts.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='clinicsurvey',
            name='phone_number',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13), otonevrolog_main.accounts.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='clinicsurvey',
            name='problem_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Describe your problem'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[otonevrolog_main.accounts.validators.validate_image_size]),
        ),
    ]
