# Generated by Django 5.1.2 on 2024-12-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clinicsurvey_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicsurvey',
            name='unique_id',
        ),
    ]
