# Generated by Django 5.1.2 on 2024-12-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_clinicsurvey_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicsurvey',
            name='age',
        ),
        migrations.RemoveField(
            model_name='clinicsurvey',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clinicsurvey',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clinicsurvey',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='clinicsurvey',
            name='problem_description',
        ),
    ]
