# Generated by Django 5.1.2 on 2024-12-08 19:34

import django.core.validators
import otonevrolog_main.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_clinicsurvey_age_remove_clinicsurvey_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsurvey',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='clinicsurvey',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[otonevrolog_main.accounts.validators.validate_email]),
        ),
        migrations.AddField(
            model_name='clinicsurvey',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='clinicsurvey',
            name='phone_number',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13), otonevrolog_main.accounts.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='clinicsurvey',
            name='problem_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Describe your problem'),
        ),
    ]
