# Generated by Django 5.1.2 on 2024-12-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clinicsurvey_age_clinicsurvey_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsurvey',
            name='ssn',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
