# Generated by Django 5.1.2 on 2024-12-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_clinicsurvey_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicsurvey',
            name='phone_number',
        ),
    ]
