# Generated by Django 5.1.2 on 2024-10-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
