# Generated by Django 5.0.4 on 2024-11-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_appointmentbooking_patient_appointmentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentresult',
            old_name='appointment',
            new_name='custom_user',
        ),
    ]
