# Generated by Django 5.1.2 on 2024-10-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_appointmentbooking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
