# Generated by Django 5.1.2 on 2024-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_appointment_appointmentresult_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
