# Generated by Django 5.1.2 on 2024-10-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_appointmentbooking_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
