# Generated by Django 5.1.2 on 2024-12-08 15:47

import django.core.validators
import django.db.models.deletion
import otonevrolog_main.web.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[otonevrolog_main.web.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='first_name',
            field=models.CharField(validators=[otonevrolog_main.web.validators.validate_name_only_letters]),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='last_name',
            field=models.CharField(validators=[otonevrolog_main.web.validators.validate_name_only_letters]),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[otonevrolog_main.web.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='second_name',
            field=models.CharField(validators=[otonevrolog_main.web.validators.validate_name_only_letters]),
        ),
        migrations.AlterField(
            model_name='appointmentresult',
            name='email',
            field=models.EmailField(max_length=30, validators=[otonevrolog_main.web.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='appointmentresult',
            name='first_name',
            field=models.CharField(max_length=30, validators=[otonevrolog_main.web.validators.validate_name_only_letters]),
        ),
        migrations.AlterField(
            model_name='appointmentresult',
            name='last_name',
            field=models.CharField(max_length=30, validators=[otonevrolog_main.web.validators.validate_name_only_letters]),
        ),
        migrations.AlterField(
            model_name='appointmentresult',
            name='phone_number',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13), otonevrolog_main.web.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, validators=[otonevrolog_main.web.validators.validate_name_only_letters]),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
