# Generated by Django 5.1.2 on 2024-11-11 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_appointmentbooking_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentresult',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=30),
        ),
        migrations.AddField(
            model_name='appointmentresult',
            name='first_name',
            field=models.CharField(default='Admin', max_length=30),
        ),
        migrations.AddField(
            model_name='appointmentresult',
            name='last_name',
            field=models.CharField(default='Admin', max_length=30),
        ),
        migrations.AddField(
            model_name='appointmentresult',
            name='phone_number',
            field=models.CharField(default='Admin Phone Number', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
