# Generated by Django 5.1.2 on 2024-10-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_appointmentslot_date_appointmentslot_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='day',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='time',
            field=models.CharField(),
        ),
    ]
