# Generated by Django 5.1.2 on 2024-12-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clinicsurvey_unique_id'),
        ('web', '0005_alter_appointmentbooking_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='clinic_survey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clinicsurvey'),
        ),
    ]
