# Generated by Django 5.1.2 on 2024-11-11 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_appointmentresult_email_appointmentresult_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentresult',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='appointmentresult',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='appointmentresult',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='appointmentresult',
            name='phone_number',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
