# Generated by Django 5.1.2 on 2024-11-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_appointmentbooking_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slot', to='web.appointmentbooking'),
        ),
    ]
