# Generated by Django 5.1.2 on 2024-12-08 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clinicsurvey_unique_id'),
        ('web', '0007_remove_appointmentbooking_clinic_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='clinic_survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_booking', to='accounts.clinicsurvey'),
        ),
    ]
