# Generated by Django 5.1.2 on 2024-11-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_stars',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
