# Generated by Django 5.1.2 on 2024-12-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_appointmentbooking_clinic_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='ssn',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
