# Generated by Django 5.1.2 on 2024-11-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_review_rating_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating_stars',
        ),
    ]
