# Generated by Django 5.1.2 on 2024-12-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_appointmentbooking_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='ssn',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
