# Generated by Django 5.1.2 on 2024-11-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_post_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
