# Generated by Django 5.1.2 on 2024-12-08 15:47

import otonevrolog_main.blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_blog_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_post_image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[otonevrolog_main.blog.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, help_text='Optional', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
